% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name untitled
%  @associatedFile /MATLAB Drive/untitled.m
%  @mostRecentlyActioned true
%  @uniqueId 08E56D39

untitled

%% @name untitledexauhstive
%  @associatedFile /MATLAB Drive/untitledexauhstive.m
%  @mostRecentlyActioned true
%  @uniqueId 2F3C3BE7

untitledexauhstive

%% @name cuntitled
%  @associatedFile /MATLAB Drive/cuntitled.m
%  @mostRecentlyActioned true
%  @uniqueId 5E99EA69

cuntitled

%% @name Fibonaaci_search
%  @associatedFile /MATLAB Drive/Fibonaaci_search.m
%  @mostRecentlyActioned true
%  @uniqueId 4E18C660

Fibonaaci_search

%% @name bisection
%  @associatedFile /MATLAB Drive/bisection.m
%  @mostRecentlyActioned true
%  @uniqueId B3810470

bisection

%% @name successivequadratic
%  @associatedFile /MATLAB Drive/successivequadratic.m
%  @mostRecentlyActioned true
%  @uniqueId 7350E8E4

successivequadratic

